version: 0.2

env:
  variables:
    AWS_REGION_2: "us-east-2"
    REACT_APP_BACKEND_API: "http://localhost:5000"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging in to docker...
      - docker login -u $username -p $password
      
      
  build:
    commands:
      - echo building prod images...
      - >
        docker build \
          -f ./Dockerfile \
          -t $username/uber-fe:prod \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_BACKEND_API=$REACT_APP_BACKEND_API \
          .
  post_build:
    commands:
    - echo pushing prod images to ecr...
    - docker push $username/uber-fe:prod
